Add validation to move in frontend
Ojself/yesnaga pull request #7
Opened 2020-08-28 21:04 UTC by Ojself

When player clicks a tile and wants to make a move, the move is being validated and sent to backend for further validation. 

An error message is displayed for the user if the request goes into catch

2020-08-29 18:30 UTC, Parnswir commented
What exactly are the problems, except that there's no answer from the server yet?

2020-08-30 20:33 UTC, Ojself commented
> What exactly are the problems, except that there's no answer from the server yet?

There's no obvious problem to be honest. The code runs as expected. But I don't know if the logic is as clever as we want it to be. Maybe there's a better approach.

2020-09-28 19:05 UTC, Parnswir requested changes

2020-09-28 19:05 UTC, Parnswir commented on routes/api/index.js
> +	// res.render('board', newBoard)
I'm working on this in parallel. I'd suggest this until I get around to actually implementing the move. This way, no matter what move you make, the default board is returned, so you can think about re-rendering and stuff :-)
```suggestion
	return res.json(BoardFactory.toObject(new Board());
```

2020-09-28 19:05 UTC, Parnswir commented on public/shapes/disc.js
> +		} */
```suggestion
		
```

2020-09-28 19:05 UTC, Parnswir commented on public/scripts/game.js
> +				});
I bet you can extract this to be a more generic error handler, that we can re-use for all the other requests (and to clean up the code a bit)

2020-09-28 19:05 UTC, Parnswir commented on public/scripts/game.js
> +			text(`${JSON.stringify(this.errorMsg)}`, 25, 150);
Why use `JSON.stringify` here?

2020-10-06 04:59 UTC, Ojself commented on public/scripts/game.js
> +			text(`${JSON.stringify(this.errorMsg)}`, 25, 150);
Good question. I removed it!

2020-10-06 17:57 UTC, Parnswir approved these changes

2020-10-06 17:57 UTC, merged